package main

import (
	"crypto/ed25519"
	"encoding/base64"
	"testing"
)

// Golden vectors GENERATED BY THE SERVER's own devicerelay package.
//
// This repo is public and the server's module is private, so the wire contract
// is mirrored here rather than imported -- which means the two can silently
// drift. These bytes are the guard: if the server changes a domain-separation
// tag, a field order, or the length-prefix framing, these fail here instead of
// the relay failing in the field with an unverifiable-signature error nobody can
// trace back to a one-character constant.
//
// Regenerate against the server, do not hand-edit.
const (
	goldServerPub      = "ebVWLo/mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ="
	goldPingSigningMsg = "AAAAHHJpbmRsZXItZGV2aWNlLXJlbGF5L3BpbmcvdjIAAAAMcmVxLWdvbGRlbi0xAAAAD21haWwuZ29vZ2xlLmNvbQAAAAhwYXNzd29yZAAAAASqu8zdAAAAAwECAwAAAAMxMjA="
	goldPingSignature  = "ZD/aExTGAiwXPxee5vnglKGXtPMQk7wpxPpCD4QfYvEkQxCbUMBIf9Ufk8kUu9iF2W1UUXuCf/HislbBGM+pBw=="
	goldSealInfo       = "cmluZGxlci1kZXZpY2UtcmVsYXktdjEfcmVxLWdvbGRlbi0xH21haWwuZ29vZ2xlLmNvbR9wYXNzd29yZA=="
	goldReleaseMsg     = "AAAAH3JpbmRsZXItZGV2aWNlLXJlbGF5L3JlbGVhc2UvdjIAAAAMcmVxLWdvbGRlbi0xAAAAAwECAwAAAASqu8zdAAAAAgkI"
)

func goldenPing(t *testing.T) secretPing {
	t.Helper()
	sig, err := base64.StdEncoding.DecodeString(goldPingSignature)
	if err != nil {
		t.Fatalf("decode signature: %v", err)
	}
	return secretPing{
		RequestID:             "req-golden-1",
		Site:                  "mail.google.com",
		SecretKind:            secretPassword,
		WorkerEphemeralPubkey: []byte{0xaa, 0xbb, 0xcc, 0xdd},
		Challenge:             []byte{0x01, 0x02, 0x03},
		TTLSeconds:            120,
		ServerSignature:       sig,
	}
}

func TestPingSigningMessageMatchesServer(t *testing.T) {
	got := base64.StdEncoding.EncodeToString(pingSigningMessage(goldenPing(t)))
	if got != goldPingSigningMsg {
		t.Fatalf("ping signing message drifted from the server\n got %s\nwant %s", got, goldPingSigningMsg)
	}
}

func TestReleaseSigningMessageMatchesServer(t *testing.T) {
	p := goldenPing(t)
	got := base64.StdEncoding.EncodeToString(
		releaseSigningMessage(p.RequestID, p.Challenge, p.WorkerEphemeralPubkey, []byte{0x09, 0x08}))
	if got != goldReleaseMsg {
		t.Fatalf("release signing message drifted from the server\n got %s\nwant %s", got, goldReleaseMsg)
	}
}

func TestSealInfoMatchesServer(t *testing.T) {
	p := goldenPing(t)
	got := base64.StdEncoding.EncodeToString(sealInfo(p.RequestID, p.Site, p.SecretKind))
	if got != goldSealInfo {
		t.Fatalf("seal info drifted from the server\n got %s\nwant %s", got, goldSealInfo)
	}
}

// The end that matters operationally: a real server-signed ping must verify with
// the server's real public key.
func TestVerifyServerSignedPing(t *testing.T) {
	pub, err := base64.StdEncoding.DecodeString(goldServerPub)
	if err != nil {
		t.Fatalf("decode pubkey: %v", err)
	}
	p := goldenPing(t)
	if !verifyPingSignature(ed25519.PublicKey(pub), p) {
		t.Fatal("a genuine server-signed ping failed verification")
	}
}

// Verification must FAIL closed on every way a ping can be wrong. Without this
// the positive test above would still pass against a verifier that returned true
// unconditionally -- which is the exact bug that would hand any caller on the
// socket a credential.
func TestVerifyPingRejectsTampering(t *testing.T) {
	pub, _ := base64.StdEncoding.DecodeString(goldServerPub)

	t.Run("tampered site", func(t *testing.T) {
		p := goldenPing(t)
		p.Site = "evil.example.com"
		if verifyPingSignature(ed25519.PublicKey(pub), p) {
			t.Fatal("a ping whose site was swapped must not verify")
		}
	})
	// The most dangerous single tamper: swapping the recipient key would make the
	// device seal the secret straight to an attacker. It is signed for exactly
	// this reason.
	t.Run("swapped worker key", func(t *testing.T) {
		p := goldenPing(t)
		p.WorkerEphemeralPubkey = []byte{0x11, 0x22, 0x33, 0x44}
		if verifyPingSignature(ed25519.PublicKey(pub), p) {
			t.Fatal("a ping whose worker key was swapped must not verify")
		}
	})
	t.Run("no signature", func(t *testing.T) {
		p := goldenPing(t)
		p.ServerSignature = nil
		if verifyPingSignature(ed25519.PublicKey(pub), p) {
			t.Fatal("an unsigned ping must not verify")
		}
	})
	t.Run("wrong signer", func(t *testing.T) {
		other, _, _ := ed25519.GenerateKey(nil)
		if verifyPingSignature(other, goldenPing(t)) {
			t.Fatal("a ping signed by another key must not verify")
		}
	})
	t.Run("no server key", func(t *testing.T) {
		if verifyPingSignature(nil, goldenPing(t)) {
			t.Fatal("verification with no server key must fail closed")
		}
	})
}

// The vault holds durable credentials, so a live one-time code can never come
// from it. Serving one would mean returning something stale as if it were fresh.
func TestOnlyDurableSecretKindsAreServed(t *testing.T) {
	for _, k := range []secretKind{secretUsername, secretPassword} {
		if !validSecretKind(k) {
			t.Fatalf("%s must be servable from the vault", k)
		}
	}
	for _, k := range []secretKind{secretEmailOTPCode, secretSMSOTPCode, secretManualCode, secretKind("nonsense")} {
		if validSecretKind(k) {
			t.Fatalf("%s must NOT be servable from the vault", k)
		}
	}
}
